mobile_base:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20  

#  joint1_position_controller:
#    type: velocity_controllers/JointVelocityController
#    joint: wheel1

#  joint2_position_controller:
#    type: velocity_controllers/JointVelocityController
#    joint: wheel2

#  joint3_position_controller:
#    type: velocity_controllers/JointVelocityController
#    joint: wheel3

  mobile_base_controller:
    type: "omni_triangle_controller/OmniDriveController"
#    type: base_simple_controller/BaseSimpleController
    wheel1: 'wheel_front'
    wheel2: 'wheel_left'
    wheel3: 'wheel_right'
    wheel_radius: 0.0325
    wheel_center: 0.161

  servo1_position_controller:
    type: position_controllers/JointPositionController
    joint: servo_1

  servo2_position_controller:
    type: position_controllers/JointPositionController
    joint: servo_2
